version: '3.3'

services:
  leantime:
    image: leantime/leantime:${LEAN_VERSION:-latest}
    container_name: leantime_app
    restart: unless-stopped
    env_file: ./.env  # Arquivo com variáveis de ambiente
    environment:
      - LEAN_DB_HOST
      - LEAN_DB_PORT
      - LEAN_DB_USER
      - LEAN_DB_PASSWORD
      - LEAN_DB_DATABASE
      - LEAN_DB_SSL
    ports:
      - "${LEAN_PORT:-8081}:80"
    volumes:
      - public_userfiles:/var/www/html/public/userfiles
      - userfiles:/var/www/html/userfiles
      - plugins:/var/www/html/plugins
      - logs:/var/www/html/storage/logs

volumes:
  public_userfiles:
  userfiles:
  plugins:
  logs:
