version: '3.3'

services:
  leantime:
    image: leantime/leantime:${LEAN_VERSION:-latest}
    container_name: leantime_app
    restart: unless-stopped
    env_file: ./.env  # Opcional se usar as variáveis diretamente abaixo
    environment:
      - LEAN_DB_HOST=interchange.proxy.rlwy.net
      - LEAN_DB_PORT=51564
      - LEAN_DB_USER=root
      - LEAN_DB_PASSWORD=pPsREsZQUTnJOJYfHCNWXKZBFVWnCJyk
      - LEAN_DB_DATABASE=railway
      - LEAN_DB_SSL=true  # SSL obrigatório para conexões externas
    ports:
      - "${LEAN_PORT:-8081}:80"
    volumes:
      - public_userfiles:/var/www/html/public/userfiles
      - userfiles:/var/www/html/userfiles
      - plugins:/var/www/html/plugins
      - logs:/var/www/html/storage/logs

volumes:
  public_userfiles:
  userfiles:
  plugins:
  logs:
